base-path = "pages"
base-url = "/version-injector-nursery"
vanguard = ["latest"]
vanguard-warning = "vanguard-warning.html"
versions = [
    "0.0.0-rc2",
    "0.0.0-rc1",
]
versions-warning = "versions-warning.html"
variants = [
    "your-variant",
    "my-variant",
]
